# Generated by Django 3.2.19 on 2023-06-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='approved',
            new_name='approve',
        ),
    ]
