# Generated by Django 3.2.19 on 2023-06-12 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230612_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='booked',
            new_name='bookedTable',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cancel',
            new_name='cancelTable',
        ),
        migrations.AlterField(
            model_name='item',
            name='tableSize',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
