# Generated by Django 3.2.19 on 2023-06-12 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20230612_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tableSize',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
