# Generated by Django 3.2.19 on 2023-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_item_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(choices=[('3PM', '3PM'), ('4PM', '4PM'), ('5PM', '5PM'), ('6PM', '6PM'), ('7PM', '7PM'), ('8PM', '8PM'), ('9PM', '9PM')], default='3PM', max_length=8),
        ),
    ]
