# Generated by Django 3.2.19 on 2023-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_item_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='HAPPY TO SEND FOR APPROVAL? TICK BOX.'),
        ),
    ]
