# Generated by Django 3.2.19 on 2023-06-12 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_item_tablesize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bookedTable',
            new_name='booked',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cancelTable',
            new_name='cancel',
        ),
        migrations.AlterField(
            model_name='item',
            name='tableSize',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
