# Generated by Django 3.2.19 on 2023-06-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=8),
        ),
    ]
