# Generated by Django 3.2.19 on 2023-06-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_table_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
