# Generated by Django 3.2.19 on 2023-06-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tableSize',
        ),
    ]
