# Generated by Django 3.2.19 on 2023-06-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_item_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
