# Generated by Django 3.2.19 on 2023-06-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_delete_welcomemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
