# Generated by Django 3.2.19 on 2023-06-30 01:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_welcomemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemodel',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='holder', max_length=255, verbose_name='img'),
        ),
    ]
