# Generated by Django 3.2.19 on 2023-06-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_welcomemodel_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomemodel',
            name='featured_image',
        ),
    ]
